In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import mpl_toolkits
from datetime import datetime
import seaborn as sn
%matplotlib inline

In [2]:
df = pd.read_csv("kc_house_data.csv")

In [3]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [4]:
df['date'] = pd.to_datetime(df['date'])

In [5]:
df['year'] = df['date'].map(lambda x: x.strftime('%Y'))
df['month'] = df['date'].map(lambda x: x.strftime('%m'))

In [6]:
df

id       date     price  bedrooms  bathrooms  sqft_living  \
0      7129300520 2014-10-13  221900.0         3       1.00         1180   
1      6414100192 2014-12-09  538000.0         3       2.25         2570   
2      5631500400 2015-02-25  180000.0         2       1.00          770   
3      2487200875 2014-12-09  604000.0         4       3.00         1960   
4      1954400510 2015-02-18  510000.0         3       2.00         1680   
...           ...        ...       ...       ...        ...          ...   
21608   263000018 2014-05-21  360000.0         3       2.50         1530   
21609  6600060120 2015-02-23  400000.0         4       2.50         2310   
21610  1523300141 2014-06-23  402101.0         2       0.75         1020   
21611   291310100 2015-01-16  400000.0         3       2.50         1600   
21612  1523300157 2014-10-15  325000.0         2       0.75         1020   

       sqft_lot  floors  waterfront  view  ...  sqft_basement  yr_built  \
0          5650     1.0           0     0  ...              0      1955   
1          7242     2.0           0     0  ...            400      1951   
2         10000     1.0           0     0  ...              0      1933   
3          5000     1.0           0     0  ...            910      1965   
4          8080     1.0           0     0  ...              0      1987   
...         ...     ...         ...   ...  ...            ...       ...   
21608      1131     3.0           0     0  ...              0      2009   
21609      5813     2.0           0     0  ...              0      2014   
21610      1350     2.0           0     0  ...              0      2009   
21611      2388     2.0           0     0  ...              0      2004   
21612      1076     2.0           0     0  ...              0      2008   

       yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  \
0                 0    98178  47.5112 -122.257           1340        5650   
1              1991    98125  47.7210 -122.319           1690        7639   
2                 0    98028  47.7379 -122.233           2720        8062   
3                 0    98136  47.5208 -122.393           1360        5000   
4                 0    98074  47.6168 -122.045           1800        7503   
...             ...      ...      ...      ...            ...         ...   
21608             0    98103  47.6993 -122.346           1530        1509   
21609             0    98146  47.5107 -122.362           1830        7200   
21610             0    98144  47.5944 -122.299           1020        2007   
21611             0    98027  47.5345 -122.069           1410        1287   
21612             0    98144  47.5941 -122.299           1020        1357   

       year  month  
0      2014     10  
1      2014     12  
2      2015     02  
3      2014     12  
4      2015     02  
...     ...    ...  
21608  2014     05  
21609  2015     02  
21610  2014     06  
21611  2015     01  
21612  2014     10  

[21613 rows x 23 columns]

In [7]:
df = df.dropna()

In [8]:
list(df.columns)

['id',
 'date',
 'price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15',
 'year',
 'month']

In [9]:
df.view.unique()

array([0, 3, 4, 2, 1], dtype=int64)

In [10]:
df.waterfront.unique()

array([0, 1], dtype=int64)

In [11]:
df.floors.unique()

array([1. , 2. , 1.5, 3. , 2.5, 3.5])

In [12]:
df.yr_renovated.unique()

array([   0, 1991, 2002, 2010, 1999, 1992, 2013, 1994, 1978, 2005, 2008,
       2003, 1984, 1954, 2014, 2011, 1974, 1983, 1945, 1990, 1988, 1957,
       1977, 1981, 1995, 2000, 1998, 1970, 1989, 2004, 1986, 2009, 2007,
       1987, 1973, 2006, 1985, 2001, 1980, 1971, 1979, 1997, 1950, 1969,
       1948, 2015, 1968, 2012, 1963, 1951, 1993, 1962, 1996, 1972, 1953,
       1955, 1982, 1956, 1940, 1976, 1946, 1975, 1958, 1964, 1959, 1960,
       1967, 1965, 1934, 1944], dtype=int64)

In [13]:
df.drop(columns=['id','date','grade','sqft_above','sqft_basement','sqft_living15','sqft_lot15'], inplace=True)

In [14]:
df

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0      221900.0         3       1.00         1180      5650     1.0   
1      538000.0         3       2.25         2570      7242     2.0   
2      180000.0         2       1.00          770     10000     1.0   
3      604000.0         4       3.00         1960      5000     1.0   
4      510000.0         3       2.00         1680      8080     1.0   
...         ...       ...        ...          ...       ...     ...   
21608  360000.0         3       2.50         1530      1131     3.0   
21609  400000.0         4       2.50         2310      5813     2.0   
21610  402101.0         2       0.75         1020      1350     2.0   
21611  400000.0         3       2.50         1600      2388     2.0   
21612  325000.0         2       0.75         1020      1076     2.0   

       waterfront  view  condition  yr_built  yr_renovated  zipcode      lat  \
0               0     0          3      1955             0    98178  47.5112   
1               0     0          3      1951          1991    98125  47.7210   
2               0     0          3      1933             0    98028  47.7379   
3               0     0          5      1965             0    98136  47.5208   
4               0     0          3      1987             0    98074  47.6168   
...           ...   ...        ...       ...           ...      ...      ...   
21608           0     0          3      2009             0    98103  47.6993   
21609           0     0          3      2014             0    98146  47.5107   
21610           0     0          3      2009             0    98144  47.5944   
21611           0     0          3      2004             0    98027  47.5345   
21612           0     0          3      2008             0    98144  47.5941   

          long  year month  
0     -122.257  2014    10  
1     -122.319  2014    12  
2     -122.233  2015    02  
3     -122.393  2014    12  
4     -122.045  2015    02  
...        ...   ...   ...  
21608 -122.346  2014    05  
21609 -122.362  2015    02  
21610 -122.299  2014    06  
21611 -122.069  2015    01  
21612 -122.299  2014    10  

[21613 rows x 16 columns]

In [15]:
df_ml = df.drop(columns=['lat','long'])

In [16]:
df.loc[df['bedrooms'] == 33]

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
15870  640000.0        33       1.75         1620      6000     1.0   

       waterfront  view  condition  yr_built  yr_renovated  zipcode      lat  \
15870           0     0          5      1947             0    98103  47.6878   

          long  year month  
15870 -122.331  2014    06

In [17]:
df.drop(df.index[15870], inplace=True)

In [18]:
df.loc[df['bedrooms'] == 33]

Empty DataFrame
Columns: [price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, yr_built, yr_renovated, zipcode, lat, long, year, month]
Index: []

In [19]:
df_ml['yr_renovated'] = df_ml['yr_renovated'].astype(bool).astype(int)
df_ml

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0      221900.0         3       1.00         1180      5650     1.0   
1      538000.0         3       2.25         2570      7242     2.0   
2      180000.0         2       1.00          770     10000     1.0   
3      604000.0         4       3.00         1960      5000     1.0   
4      510000.0         3       2.00         1680      8080     1.0   
...         ...       ...        ...          ...       ...     ...   
21608  360000.0         3       2.50         1530      1131     3.0   
21609  400000.0         4       2.50         2310      5813     2.0   
21610  402101.0         2       0.75         1020      1350     2.0   
21611  400000.0         3       2.50         1600      2388     2.0   
21612  325000.0         2       0.75         1020      1076     2.0   

       waterfront  view  condition  yr_built  yr_renovated  zipcode  year  \
0               0     0          3      1955             0    98178  2014   
1               0     0          3      1951             1    98125  2014   
2               0     0          3      1933             0    98028  2015   
3               0     0          5      1965             0    98136  2014   
4               0     0          3      1987             0    98074  2015   
...           ...   ...        ...       ...           ...      ...   ...   
21608           0     0          3      2009             0    98103  2014   
21609           0     0          3      2014             0    98146  2015   
21610           0     0          3      2009             0    98144  2014   
21611           0     0          3      2004             0    98027  2015   
21612           0     0          3      2008             0    98144  2014   

      month  
0        10  
1        12  
2        02  
3        12  
4        02  
...     ...  
21608    05  
21609    02  
21610    06  
21611    01  
21612    10  

[21613 rows x 14 columns]

In [20]:
df_ml.describe()

price      bedrooms     bathrooms   sqft_living      sqft_lot  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  2.161300e+04   
mean   5.400881e+05      3.370842      2.114757   2079.899736  1.510697e+04   
std    3.671272e+05      0.930062      0.770163    918.440897  4.142051e+04   
min    7.500000e+04      0.000000      0.000000    290.000000  5.200000e+02   
25%    3.219500e+05      3.000000      1.750000   1427.000000  5.040000e+03   
50%    4.500000e+05      3.000000      2.250000   1910.000000  7.618000e+03   
75%    6.450000e+05      4.000000      2.500000   2550.000000  1.068800e+04   
max    7.700000e+06     33.000000      8.000000  13540.000000  1.651359e+06   

             floors    waterfront          view     condition      yr_built  \
count  21613.000000  21613.000000  21613.000000  21613.000000  21613.000000   
mean       1.494309      0.007542      0.234303      3.409430   1971.005136   
std        0.539989      0.086517      0.766318      0.650743     29.373411   
min        1.000000      0.000000      0.000000      1.000000   1900.000000   
25%        1.000000      0.000000      0.000000      3.000000   1951.000000   
50%        1.500000      0.000000      0.000000      3.000000   1975.000000   
75%        2.000000      0.000000      0.000000      4.000000   1997.000000   
max        3.500000      1.000000      4.000000      5.000000   2015.000000   

       yr_renovated       zipcode  
count  21613.000000  21613.000000  
mean       0.042289  98077.939805  
std        0.201253     53.505026  
min        0.000000  98001.000000  
25%        0.000000  98033.000000  
50%        0.000000  98065.000000  
75%        0.000000  98118.000000  
max        1.000000  98199.000000

In [21]:
list(df_ml.columns)

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'year',
 'month']

In [22]:
y = df_ml['price']
X = df_ml[['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'year',
 'month'
]]

In [23]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [24]:
model = LinearRegression()

In [25]:
model.fit(X_train, y_train)

LinearRegression()

In [26]:
score = model.score(X, y)
print(f"R2 Score: {score}")

R2 Score: 0.5987828483185597


In [27]:
coeff_df = pd.DataFrame(model.coef_, X.columns, columns=['Coefficient'])  
coeff_df

Coefficient
bedrooms      -56024.756064
bathrooms      60835.739893
sqft_living      275.254481
sqft_lot          -0.340061
floors         59586.504682
waterfront    509080.734050
view           59717.481040
condition      16257.950428
yr_built       -2846.279451
yr_renovated   24503.905173
zipcode          -21.497227
year           27150.898226
month            585.632082

In [40]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators = 100, random_state=42)
regressor.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [41]:
regressor.score(X_test, y_test)

0.7624661171457305

In [52]:
# Use the forest's predict method on the test data
predictions = regressor.predict(X_test)

# Print out the mean absolute error (mae)
from sklearn.metrics import mean_absolute_error

print('Mean Absolute Error:' ,mean_absolute_error(y_test, predictions))

Mean Absolute Error: 94784.18692244141


In [54]:
mse = mean_squared_error(y_test, predictions)
print('Mean Squared Error: ', mse)

Mean Squared Error:  35909591459.51376


In [58]:
import math 
root_mean_sqr = math.sqrt(mse)
print('Root Mean Square: ', root_mean_sqr)

Root Mean Square:  189498.26241819147


In [44]:
# The mean absolute percentage error (MAPE) is a statistical measure of how accurate a forecast system is. 
# It measures this accuracy as a percentage, and can be calculated as the average absolute percent error
# for each time period minus actual values divided by actual values.

# Calculate the absolute errors
errors = abs(predictions - y_test)

# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
print('MAPE:', mape.mean())

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

MAPE: 17.1761296198183
Accuracy: 82.82 %.


In [46]:
feature_names = X
sorted(zip(regressor.feature_importances_, feature_names), reverse=True)

[(0.5811723425507357, 'sqft_living'),
 (0.1514156435982179, 'zipcode'),
 (0.06776584550188071, 'yr_built'),
 (0.054328120911239376, 'sqft_lot'),
 (0.03558678598133811, 'view'),
 (0.029835996382049156, 'bathrooms'),
 (0.026012295814620372, 'waterfront'),
 (0.017966281814045963, 'month'),
 (0.01208686820302045, 'bedrooms'),
 (0.009824842981779826, 'floors'),
 (0.0077004685041468495, 'condition'),
 (0.0032090501501777693, 'year'),
 (0.003095457606747792, 'yr_renovated')]

In [47]:
sum(regressor.feature_importances_)

1.0000000000000002

In [48]:
df_ml.to_csv('clean1.csv',index=False)

In [50]:
df_ml.iloc[:,1:]

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0             3       1.00         1180      5650     1.0           0     0   
1             3       2.25         2570      7242     2.0           0     0   
2             2       1.00          770     10000     1.0           0     0   
3             4       3.00         1960      5000     1.0           0     0   
4             3       2.00         1680      8080     1.0           0     0   
...         ...        ...          ...       ...     ...         ...   ...   
21608         3       2.50         1530      1131     3.0           0     0   
21609         4       2.50         2310      5813     2.0           0     0   
21610         2       0.75         1020      1350     2.0           0     0   
21611         3       2.50         1600      2388     2.0           0     0   
21612         2       0.75         1020      1076     2.0           0     0   

       condition  yr_built  yr_renovated  zipcode  year month  
0              3      1955             0    98178  2014    10  
1              3      1951             1    98125  2014    12  
2              3      1933             0    98028  2015    02  
3              5      1965             0    98136  2014    12  
4              3      1987             0    98074  2015    02  
...          ...       ...           ...      ...   ...   ...  
21608          3      2009             0    98103  2014    05  
21609          3      2014             0    98146  2015    02  
21610          3      2009             0    98144  2014    06  
21611          3      2004             0    98027  2015    01  
21612          3      2008             0    98144  2014    10  

[21613 rows x 13 columns]